#!/usr/bin/env python

import gitutils

import argparse

def main(push):
    if not gitutils.in_git_repo():
        return

    original_branch = gitutils.current_branch()

    upstreams = gitutils.upstreams()

    branch = str(original_branch)
    while True:
        upstream = upstreams[branch]

        if not gitutils.is_remote(branch) and not upstream:
            break

        if gitutils.is_remote(upstream):
            if push:
                print "git push"
                #gitutils.git("push")
            break

        print "git checkout", upstream
        print "git merge", branch
        #gitutils.git("checkout", [upstream, "-q"])
        #gitutils.git("merge", [branch])

        branch = upstream

    print "git checkout", original_branch
    gitutils.git("checkout", [original_branch, "-q"])

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("-p", "--push", help="Push final branch to origin, if applicable", action="store_true")
    args = parser.parse_args()

    main(args.push)
