#!/usr/bin/env python

import gitutils

import argparse

"""
    1) Save original branch
    2) Set branch to be original branch
    3) Loop
        a) Get upstream
        b) If upstream is None, we're at 
"""

def main(push):
    original_branch = gitutils.current_branch()

    branch = str(original_branch)
    tree = [branch]
    while True:
        upstream = gitutils.upstream(branch)
        if not upstream:
            break
        tree.append(upstream)
        branch = upstream

    #gitutils.git("checkout", [original_branch, "-q"])

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("-p", "--push", help="Push final branch to origin, if applicable", action="store_true")
    args = parser.parse_args()

    main(args.push)
